// javagen generates the per-version Java protocol data from vanilla's own output:
//
//   - packetid.go: a constant for every packet id, from Mojang's packets.json report
//     (java -DbundlerMainClass=net.minecraft.data.Main -jar server.jar --reports).
//   - registries.go: every synchronised registry's entries in the order vanilla sends them, decoded
//     from a pktcap capture of a vanilla join. The order is the network id (a chunk's biome ids
//     index the biome registry, for example).
//   - vanilla/: the configuration packets vanilla sends that we send unchanged (feature flags,
//     known packs, registry data, tags), embedded with an ordered list.
//
//	go run ./java/cmd/javagen -packets packets.json -capture capture/vanilla/conn001 -out java/v777 -pkg v777
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ezchr/go-mc/java/wire"
)

func camel(name string) string {
	name = strings.TrimPrefix(name, "minecraft:")
	var b strings.Builder
	for _, part := range strings.FieldsFunc(name, func(r rune) bool { return r == '_' || r == '/' || r == '.' }) {
		b.WriteString(strings.ToUpper(part[:1]) + part[1:])
	}
	return b.String()
}

func writeGo(path string, src []byte) {
	out, err := format.Source(src)
	if err != nil {
		os.WriteFile(path+".broken", src, 0o644)
		log.Fatalf("%s: %v", path, err)
	}
	if err := os.WriteFile(path, out, 0o644); err != nil {
		log.Fatal(err)
	}
}

func genPacketIDs(packets, out, pkg string) {
	var raw map[string]map[string]map[string]struct {
		ID int32 `json:"protocol_id"`
	}
	b, err := os.ReadFile(packets)
	if err != nil {
		log.Fatal(err)
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		log.Fatal(err)
	}
	var src bytes.Buffer
	fmt.Fprintf(&src, "// Code generated by javagen from Mojang's packets.json report. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	for _, state := range []string{"handshake", "status", "login", "configuration", "play"} {
		for _, dir := range []string{"clientbound", "serverbound"} {
			pks := raw[state][dir]
			if len(pks) == 0 {
				continue
			}
			type e struct {
				name string
				id   int32
			}
			var list []e
			for n, p := range pks {
				list = append(list, e{n, p.ID})
			}
			sort.Slice(list, func(i, j int) bool { return list[i].id < list[j].id })
			prefix := camel(dir) + camel(state)
			fmt.Fprintf(&src, "// %s %s packets.\nconst (\n", camel(state), dir)
			for _, p := range list {
				fmt.Fprintf(&src, "\t%s%s int32 = %#02x // %s\n", prefix, camel(p.name), p.id, p.name)
			}
			src.WriteString(")\n\n")
		}
	}
	writeGo(filepath.Join(out, "packetid.go"), src.Bytes())
}

// genConfiguration copies the vanilla configuration packets and decodes the registries.
func genConfiguration(capture, out, pkg string) {
	files, err := filepath.Glob(filepath.Join(capture, "*_S_configuration_*.bin"))
	if err != nil || len(files) == 0 {
		log.Fatalf("no clientbound configuration packets in %s", capture)
	}
	sort.Strings(files) // the file names start with the packet's sequence number
	keep := map[string]bool{
		"update_enabled_features": true, "select_known_packs": true,
		"registry_data": true, "update_tags": true,
	}
	vdir := filepath.Join(out, "vanilla")
	os.RemoveAll(vdir)
	os.MkdirAll(vdir, 0o755)
	var list, regs bytes.Buffer
	type registry struct {
		name    string
		entries []string
	}
	var registries []registry
	for i, f := range files {
		base := filepath.Base(f)
		packet := base[strings.Index(base, "minecraft_")+len("minecraft_") : len(base)-len(".bin")]
		if !keep[packet] {
			continue
		}
		body, err := os.ReadFile(f)
		if err != nil {
			log.Fatal(err)
		}
		name := fmt.Sprintf("%02d_%s.bin", i, packet)
		os.WriteFile(filepath.Join(vdir, name), body, 0o644)
		fmt.Fprintf(&list, "\t{ClientboundConfiguration%s, %q},\n", camel(packet), name)
		if packet == "registry_data" {
			r := wire.NewReader(body)
			reg := registry{name: r.String(32767)}
			n := int(r.VarInt())
			for j := 0; j < n; j++ {
				reg.entries = append(reg.entries, r.String(32767))
				if r.Bool() {
					log.Fatalf("%s entry %s carries data: known packs not in use?", reg.name, reg.entries[j])
				}
			}
			if r.Err != nil || r.Len() != 0 {
				log.Fatalf("%s: registry_data didn't decode cleanly (err %v, %d bytes left)", base, r.Err, r.Len())
			}
			registries = append(registries, reg)
		}
	}
	var src bytes.Buffer
	fmt.Fprintf(&src, "// Code generated by javagen from a vanilla join capture. DO NOT EDIT.\n\npackage %s\n\nimport \"embed\"\n\n", pkg)
	src.WriteString("//go:embed vanilla/*.bin\nvar vanillaFS embed.FS\n\n")
	src.WriteString("// vanillaConfiguration is the configuration packets vanilla sends that we send unchanged, in order.\n")
	src.WriteString("var vanillaConfiguration = []struct {\n\tID   int32\n\tFile string\n}{\n")
	src.Write(list.Bytes())
	src.WriteString("}\n")
	writeGo(filepath.Join(out, "configuration.go"), src.Bytes())

	fmt.Fprintf(&regs, "// Code generated by javagen from a vanilla join capture. DO NOT EDIT.\n\npackage %s\n\n", pkg)
	regs.WriteString("// Registries holds every synchronised registry's entries in network-id order.\nvar Registries = map[string][]string{\n")
	for _, r := range registries {
		fmt.Fprintf(&regs, "\t%q: {\n", r.name)
		for _, e := range r.entries {
			fmt.Fprintf(&regs, "\t\t%q,\n", e)
		}
		regs.WriteString("\t},\n")
	}
	regs.WriteString("}\n")
	writeGo(filepath.Join(out, "registries.go"), regs.Bytes())
	log.Printf("configuration: %d packets kept, %d registries", strings.Count(list.String(), "\n"), len(registries))
}

func main() {
	packets := flag.String("packets", "", "Mojang packets.json")
	capture := flag.String("capture", "", "pktcap connection folder of a vanilla join")
	out := flag.String("out", "", "output package folder")
	pkg := flag.String("pkg", "", "package name")
	flag.Parse()
	if *packets == "" || *capture == "" || *out == "" || *pkg == "" {
		flag.Usage()
		os.Exit(2)
	}
	os.MkdirAll(*out, 0o755)
	genPacketIDs(*packets, *out, *pkg)
	genConfiguration(*capture, *out, *pkg)
}
