package main

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"slices"
	"sort"
	"strconv"
	"strings"
)

const decisionsHeader = `# javamap decisions: every Bedrock -> Java mapping by name and properties. Generated by javamapupdate;
# do not edit (change internal/javamapupdate/handrules.go and rerun). The _gen.go tables are compiled from this
# file, and the next update carries it over. Fields are tab separated, values space separated; names without a
# namespace are minecraft:, - is an empty list. Origin: geyser = from the GeyserMC-based javamapgen; auto:<rule> =
# chosen by javamapupdate's rules; hand = handrules.go; miss = no rule applied. Carried decisions keep their origin.
#
# B <Bedrock name> <Bedrock properties>  <Java block> <Java properties>  <origin>
#   <Bedrock values>  <Java values> | @<other Java state>  [<origin>]
# i <Bedrock item>[@meta]  <Java item>  <origin>
# g <Bedrock biome id>  <Java biome>  <origin>
# d <Java block or Bedrock name>  <properties>  <source>      (javamap.NeighbourDependent)
`

// writeDecisions writes decisions.txt. Blocks are grouped per Bedrock name: a header line names the Bedrock
// properties, the Java block most states map to with its properties, and the most common origin; each state is then
// one line of Bedrock values and Java values (or @<other Java state>), plus its origin when that differs.
func writeDecisions(path string, t *prevTables) {
	var b bytes.Buffer
	b.WriteString(decisionsHeader)
	fmt.Fprintf(&b, "java\t%s\n", t.java)
	type st struct {
		vals   []string
		java   string
		origin string
	}
	var names []string
	groups := map[string][]st{}
	propNames := map[string][]string{}
	for _, d := range t.blocks {
		r, err := parseKeyRaw(d.key)
		check(err)
		if _, ok := groups[r.name]; !ok {
			names = append(names, r.name)
			propNames[r.name] = r.keys
		} else if !slices.Equal(propNames[r.name], r.keys) {
			log.Fatalf("Bedrock block %s has states with different property names", r.name)
		}
		groups[r.name] = append(groups[r.name], st{r.vals, d.java, d.origin})
	}
	sort.Strings(names)
	for _, n := range names {
		g := groups[n]
		blocks, origins := map[string]int{}, map[string]int{}
		for _, s := range g {
			jb, _ := parseStateString(s.java)
			blocks[jb]++
			origins[s.origin]++
		}
		hb, ho := mostCommon(blocks), mostCommon(origins)
		var hp []string
		for _, s := range g {
			if jb, props := parseStateString(s.java); jb == hb {
				hp = sortedKeys(props)
				break
			}
		}
		fmt.Fprintf(&b, "B\t%s %s\t%s %s\t%s\n", short(n), list(propNames[n]), short(hb), list(hp), ho)
		sort.SliceStable(g, func(i, j int) bool { return strings.Join(g[i].vals, " ") < strings.Join(g[j].vals, " ") })
		for _, s := range g {
			jb, props := parseStateString(s.java)
			java := "@" + short(s.java)
			if jb == hb && slices.Equal(sortedKeys(props), hp) {
				vs := make([]string, len(hp))
				for i, k := range hp {
					vs[i] = props[k]
				}
				java = list(vs)
			}
			fmt.Fprintf(&b, "\t%s\t%s", list(s.vals), java)
			if s.origin != ho {
				fmt.Fprintf(&b, "\t%s", s.origin)
			}
			b.WriteByte('\n')
		}
	}
	for _, d := range t.items {
		k := short(d.name)
		if d.hasMeta {
			k += "@" + strconv.Itoa(d.meta)
		}
		fmt.Fprintf(&b, "i\t%s\t%s\t%s\n", k, short(d.java), d.origin)
	}
	for _, d := range t.biomes {
		fmt.Fprintf(&b, "g\t%d\t%s\t%s\n", d.id, short(d.java), d.origin)
	}
	for _, d := range t.deps {
		fmt.Fprintf(&b, "d\t%s\t%s\t%s\n", short(d.block), strings.Join(d.props, ","), d.source)
	}
	check(os.WriteFile(path, b.Bytes(), 0o644))
}

func readDecisions(path string) *prevTables {
	f := must(os.Open(path))
	defer f.Close()
	t := &prevTables{source: "decisions.txt"}
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	line := 0
	var cur struct {
		name, block, origin string
		keys, jkeys         []string
	}
	for sc.Scan() {
		line++
		s := sc.Text()
		if s == "" || s[0] == '#' {
			continue
		}
		f := strings.Split(s, "\t")
		bad := func() { log.Fatalf("%s:%d: bad line %q", path, line, s) }
		switch {
		case f[0] == "java" && len(f) == 2:
			t.java = f[1]
		case f[0] == "B" && len(f) == 4:
			b, j := strings.Fields(f[1]), strings.Fields(f[2])
			if len(b) < 2 || len(j) < 2 {
				bad()
			}
			cur.name, cur.keys = long(b[0]), unlist(strings.Join(b[1:], " "))
			cur.block, cur.jkeys = long(j[0]), unlist(strings.Join(j[1:], " "))
			cur.origin = f[3]
		case f[0] == "" && (len(f) == 3 || len(f) == 4):
			vals := splitValues(f[1])
			if cur.name == "" || len(vals) != len(cur.keys) {
				bad()
			}
			var kb strings.Builder
			kb.WriteString(cur.name)
			kb.WriteByte('[')
			for i, k := range cur.keys {
				if i > 0 {
					kb.WriteByte(',')
				}
				kb.WriteString(k + "=" + vals[i])
			}
			kb.WriteByte(']')
			var java string
			if rest, ok := strings.CutPrefix(f[2], "@"); ok {
				java = long(rest)
			} else {
				jv := unlist(f[2])
				if len(jv) != len(cur.jkeys) {
					bad()
				}
				props := map[string]string{}
				for i, k := range cur.jkeys {
					props[k] = jv[i]
				}
				java = stateString(cur.block, props)
			}
			origin := cur.origin
			if len(f) == 4 {
				origin = f[3]
			}
			t.blocks = append(t.blocks, prevBlock{key: kb.String(), java: java, origin: origin})
		case f[0] == "i" && len(f) == 4:
			it := prevItem{name: long(f[1]), java: long(f[2]), origin: f[3]}
			if n, m, ok := strings.Cut(f[1], "@"); ok {
				it.name, it.hasMeta = long(n), true
				it.meta = must(strconv.Atoi(m))
			}
			t.items = append(t.items, it)
		case f[0] == "g" && len(f) == 4:
			t.biomes = append(t.biomes, prevBiome{id: must(strconv.Atoi(f[1])), java: long(f[2]), origin: f[3]})
		case f[0] == "d" && len(f) == 4:
			t.deps = append(t.deps, dep{block: long(f[1]), props: strings.Split(f[2], ","), source: f[3]})
		default:
			bad()
		}
	}
	check(sc.Err())
	if t.java == "" {
		log.Fatalf("%s: no java line", path)
	}
	return t
}

func list(s []string) string {
	if len(s) == 0 {
		return "-"
	}
	return strings.Join(s, " ")
}

func unlist(s string) []string {
	if s == "-" || s == "" {
		return nil
	}
	return strings.Split(s, " ")
}

// splitValues splits space separated Bedrock values, keeping quoted strings (which may hold spaces) whole.
func splitValues(s string) []string {
	if s == "-" {
		return nil
	}
	var out []string
	for s != "" {
		if strings.HasPrefix(s, `"`) {
			q := must(strconv.QuotedPrefix(s))
			out = append(out, q)
			s = strings.TrimPrefix(s[len(q):], " ")
			continue
		}
		v, rest, _ := strings.Cut(s, " ")
		out = append(out, v)
		s = rest
	}
	return out
}

func mostCommon(m map[string]int) string {
	best, bestN := "", -1
	for _, k := range sortedKeys(m) {
		if m[k] > bestN {
			best, bestN = k, m[k]
		}
	}
	return best
}

// rawKey is a stateKey split into name, sorted property names and the values as written (strings quoted).
type rawKey struct {
	name string
	keys []string
	vals []string
}

func parseKeyRaw(key string) (rawKey, error) {
	s, err := parseKey(key)
	if err != nil {
		return rawKey{}, err
	}
	r := rawKey{name: s.name, keys: sortedKeys(s.props)}
	inner := strings.TrimSuffix(key[len(s.name)+1:], "]")
	for inner != "" {
		_, v, _ := strings.Cut(inner, "=")
		if strings.HasPrefix(v, `"`) {
			q := must(strconv.QuotedPrefix(v))
			r.vals = append(r.vals, q)
			inner = strings.TrimPrefix(v[len(q):], ",")
			continue
		}
		val, after, _ := strings.Cut(v, ",")
		r.vals = append(r.vals, val)
		inner = after
	}
	return r, nil
}
