package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"slices"
	"sort"
)

func genHeader(javaVer string) string {
	return fmt.Sprintf("// Code generated by javamapupdate from decisions.txt and the Mojang %s reports. DO NOT EDIT.\n\npackage javamap\n\n", javaVer)
}

func writeBlocks(dir, javaVer string, jd *javaData, br *blocksResult) {
	ds := slices.Clone(br.decisions)
	slices.SortFunc(ds, func(a, b blockDecision) int { return int(int64(a.df.hash) - int64(b.df.hash)) })
	var b bytes.Buffer
	b.WriteString(genHeader(javaVer))
	fmt.Fprintf(&b, "// JavaStateCount is the number of Java %s block states (the direct palette size).\nconst JavaStateCount = %d\n\n", javaVer, len(jd.states))
	fmt.Fprintf(&b, "// Java state ids of a few blocks the runtime needs.\nconst (\n\tJavaAir int32 = %d\n\tJavaStone int32 = %d\n\tJavaWater int32 = %d\n)\n\n",
		jd.blocks["minecraft:air"].def, jd.blocks["minecraft:stone"].def, jd.blocks["minecraft:water"].def)
	b.WriteString("// stateTable holds hash<<32 | javaState for every Bedrock state Dragonfly registers, sorted by hash.\n" +
		"// hash is the Bedrock network block hash (FNV-1a of the name + sorted states NBT), i.e. the state identity.\n")
	b.WriteString("var stateTable = [...]uint64{\n")
	for i, d := range ds {
		if i > 0 && d.df.hash == ds[i-1].df.hash {
			log.Fatalf("duplicate network hash %x", d.df.hash)
		}
		fmt.Fprintf(&b, "0x%08x%08x,", d.df.hash, uint32(d.java))
		if i%6 == 5 {
			b.WriteByte('\n')
		}
	}
	b.WriteString("\n}\n\n")
	b.WriteString("// nameDefault maps a Bedrock block name to a Java state, for states missing from stateTable.\nvar nameDefault = map[string]int32{\n")
	for _, k := range sortedKeys(br.nameDefault) {
		fmt.Fprintf(&b, "%q: %d,\n", k, br.nameDefault[k])
	}
	b.WriteString("}\n\n")
	b.WriteString("// waterlogRanges lists Java blocks with a waterlogged property: [first, end) state ids and the id distance\n" +
		"// between a waterlogged=true state and its waterlogged=false twin.\nvar waterlogRanges = [...][3]int32{\n")
	for _, w := range br.waterlog {
		fmt.Fprintf(&b, "{%d, %d, %d},\n", w[0], w[1], w[2])
	}
	b.WriteString("}\n\n")
	b.WriteString("// neighbourDependent lists Java blocks whose state the Bedrock state does not fully determine.\nvar neighbourDependent = []Dependency{\n")
	for _, d := range br.deps {
		fmt.Fprintf(&b, "{Block: %q, Properties: %#v, Source: %s},\n", d.block, d.props, d.source)
	}
	b.WriteString("}\n")
	writeGoFile(dir, "blocks_gen.go", b.Bytes())
}

func writeItems(dir, javaVer string, reg javaRegistries, ir *itemsResult) {
	var b bytes.Buffer
	b.WriteString(genHeader(javaVer))
	fmt.Fprintf(&b, "// JavaItemCount is the number of Java %s items.\nconst JavaItemCount = %d\n\n", javaVer, len(reg.items))
	fmt.Fprintf(&b, "// Java item ids the runtime needs.\nconst (\n\tJavaItemAir int32 = %d\n\tJavaItemBarrier int32 = %d\n)\n\n", reg.items["minecraft:air"], reg.items["minecraft:barrier"])
	var byName, byMeta []itemDecision
	for _, e := range ir.entries {
		if e.hasMeta {
			byMeta = append(byMeta, e)
		} else {
			byName = append(byName, e)
		}
	}
	b.WriteString("// itemByName maps a Bedrock item name to a Java item id when the meta does not select the item.\nvar itemByName = map[string]int32{\n")
	sort.Slice(byName, func(i, j int) bool { return byName[i].name < byName[j].name })
	for _, e := range byName {
		fmt.Fprintf(&b, "%q: %d,\n", e.name, reg.items[e.java])
	}
	b.WriteString("}\n\n// itemByMeta maps Bedrock items whose meta selects the Java item (banners, beds, ...).\nvar itemByMeta = map[itemKey]int32{\n")
	// Sorted as the strings "name@meta", like the old generator.
	sort.Slice(byMeta, func(i, j int) bool { return itemLabel(byMeta[i]) < itemLabel(byMeta[j]) })
	for _, e := range byMeta {
		fmt.Fprintf(&b, "{%q, %d}: %d,\n", e.name, e.meta, reg.items[e.java])
	}
	b.WriteString("}\n")
	writeGoFile(dir, "items_gen.go", b.Bytes())
}

func writeBiomes(dir, javaVer string, bi *biomesResult) {
	var b bytes.Buffer
	b.WriteString(genHeader(javaVer))
	b.WriteString("// biomeNames maps a Bedrock biome id to the Java biome key.\nvar biomeNames = map[int]string{\n")
	for _, e := range bi.entries {
		fmt.Fprintf(&b, "%d: %q,\n", e.id, e.java)
	}
	b.WriteString("}\n")
	writeGoFile(dir, "biomes_gen.go", b.Bytes())
}

func writeGoFile(dir, name string, src []byte) {
	f, err := format.Source(src)
	if err != nil {
		os.WriteFile(filepath.Join(dir, name+".broken"), src, 0o644)
		log.Fatalf("format %s: %v", name, err)
	}
	check(os.WriteFile(filepath.Join(dir, name), f, 0o644))
}

// decisionsOf builds the tables written to decisions.txt.
func decisionsOf(javaVer string, jd *javaData, br *blocksResult, ir *itemsResult, bi *biomesResult) *prevTables {
	t := &prevTables{java: javaVer}
	for _, d := range br.decisions {
		t.blocks = append(t.blocks, prevBlock{key: d.df.key, java: jd.str(d.java), origin: d.origin})
	}
	sort.Slice(t.blocks, func(i, j int) bool { return t.blocks[i].key < t.blocks[j].key })
	for _, e := range ir.entries {
		t.items = append(t.items, prevItem{name: e.name, meta: e.meta, hasMeta: e.hasMeta, java: e.java, origin: e.origin})
	}
	for _, e := range bi.entries {
		t.biomes = append(t.biomes, prevBiome{id: e.id, java: e.java, origin: e.origin})
	}
	t.deps = br.deps
	return t
}

func sortedKeys[V any](m map[string]V) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

func must[T any](v T, err error) T {
	check(err)
	return v
}

func check(err error) {
	if err != nil {
		log.Fatal(err)
	}
}
