package main

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
)

type runInfo struct {
	javaVer    string
	prevJava   string
	prevSource string
	geyserDir  string
}

func writeReport(dir string, ri runInfo, jd *javaData, br *blocksResult, ir *itemsResult, bi *biomesResult, sr *soundsResult, gc *geyserCheck) {
	var b bytes.Buffer
	p := func(format string, a ...any) { fmt.Fprintf(&b, format, a...) }
	p("# javamap mapping report\n\n")
	p("Generated by `internal/javamapupdate` (do not edit by hand; see `server/java/UPDATING.md`).\n")
	p("Inputs: previous decisions for Java %s (%s), the Mojang %s reports, Dragonfly's default registries", ri.prevJava, ri.prevSource, ri.javaVer)
	if ri.geyserDir != "" {
		p(", GeyserMC mappings as a cross-check only")
	}
	p(".\n\n")

	// ---- Summary
	status := map[string]int{}
	strat := map[string]int{}
	low := 0
	for _, d := range br.decisions {
		status[d.status]++
		if d.pred != nil {
			strat[d.pred.strategy]++
			if len(d.pred.low) > 0 {
				low++
			}
		}
	}
	p("## Summary\n\n| Blocks | count |\n|---|---:|\n")
	p("| Dragonfly Bedrock states | %d |\n| Java %s states | %d |\n", len(br.decisions), ri.javaVer, len(jd.states))
	p("| carried over unchanged | %d |\n| carried, Java properties changed (closest state) | %d |\n| carried, Java block renamed | %d |\n",
		status[statusCarried], status[statusCarriedClosest], status[statusCarriedRenamed])
	p("| carried, Java block missing in %s: stand-in (**review**) | %d |\n", ri.javaVer, status[statusCarriedSubst])
	p("| **new decisions** | **%d** |\n", status[statusNew])
	for _, k := range sortedKeys(strat) {
		p("| ... by `%s` | %d |\n", k, strat[k])
	}
	p("| ... low-confidence guesses | %d |\n", low)
	p("| previous decisions for states Dragonfly no longer registers (dropped) | %d |\n", len(br.dropped))
	p("| Java blocks with waterlogged ranges | %d |\n\n", len(br.waterlog))

	itemNew := map[string]int{}
	for _, e := range ir.newOnes {
		itemNew[e.origin]++
	}
	p("| Items | count |\n|---|---:|\n| Java %s items | %d |\n| Dragonfly items (name, meta) | %d |\n", ri.javaVer, ir.javaCount, ir.dfCount)
	p("| ... resolved by (name, meta) | %d |\n| ... resolved by name | %d |\n| ... unmapped (barrier) | %d |\n", ir.dfByMeta, ir.dfByName, len(ir.misses))
	p("| table entries (incl. Bedrock names Dragonfly lacks) | %d |\n| **new decisions** | **%d** |\n", len(ir.entries), len(ir.newOnes))
	for _, k := range sortedKeys(itemNew) {
		p("| ... by `%s` | %d |\n", k, itemNew[k])
	}
	p("| previous decisions dropped | %d |\n\n", len(ir.dropped))
	p("| Biomes | count |\n|---|---:|\n| Java %s biomes | %d |\n| Dragonfly biomes | %d |\n| table entries | %d |\n| **new decisions** | **%d** |\n| previous decisions dropped | %d |\n\n",
		ri.javaVer, bi.javaCount, bi.dfCount, len(bi.entries), len(bi.newOnes), len(bi.dropped))
	if sr != nil {
		p("| Sounds (`%s`) | count |\n|---|---:|\n| Bedrock -> Java sound names kept | %d |\n| renamed | %d |\n| dropped (Java event gone) | %d |\n\n",
			filepath.Base(sr.path), len(sr.pairs), len(sr.renamed), len(sr.dropped))
	}

	// ---- Review
	p("## For review\n\n")
	p("Everything below was decided automatically in this run or needs a human. Fix a wrong decision by adding a\n")
	p("hand rule (`internal/javamapupdate/handrules.go`) and deleting its lines from `decisions.txt`, then rerun.\n\n")

	p("### New block decisions (%d states)\n\n", status[statusNew])
	if status[statusNew] == 0 {
		p("None.\n\n")
	} else {
		type grp struct {
			name   string
			states int
			java   map[string]bool
			strat  map[string]bool
			props  map[string]bool
			low    map[string]bool
			notes  map[string]bool
			sample string
		}
		groups := map[string]*grp{}
		for _, d := range br.decisions {
			if d.status != statusNew {
				continue
			}
			g := groups[d.df.b.name]
			if g == nil {
				g = &grp{name: d.df.b.name, java: map[string]bool{}, strat: map[string]bool{}, props: map[string]bool{}, low: map[string]bool{}, notes: map[string]bool{}}
				g.sample = fmt.Sprintf("`%s` -> `%s`", short(d.df.key), short(jd.str(d.java)))
				groups[d.df.b.name] = g
			}
			g.states++
			g.java[short(jd.states[d.java].block)] = true
			g.strat[d.pred.strategy] = true
			for k, v := range d.pred.props {
				g.props[k+" <- "+v] = true
			}
			for _, l := range d.pred.low {
				g.low[l] = true
			}
			if d.note != "" {
				g.notes[d.note] = true
			}
		}
		p("Per Bedrock name: Java blocks, how the block was chosen, how each Java property was chosen\n")
		p("(`level:source score`), one example state, and low-confidence reasons (**LOW**).\n\n")
		for _, n := range sortedKeys(groups) {
			g := groups[n]
			p("- **%s** (%d) -> %s; block by %s", short(n), g.states, strings.Join(sortedKeys(g.java), ", "), strings.Join(sortedKeys(g.strat), ", "))
			if len(g.props) > 0 {
				p("; props %s", strings.Join(sortedKeys(g.props), "; "))
			}
			p(". %s", g.sample)
			if len(g.notes) > 0 {
				p(" (%s)", strings.Join(sortedKeys(g.notes), "; "))
			}
			if len(g.low) > 0 {
				p(". **LOW**: %s", strings.Join(sortedKeys(g.low), "; "))
			}
			p("\n")
		}
		p("\n")
	}

	var misses []string
	for _, d := range br.decisions {
		if d.pred != nil && d.pred.strategy == stratMiss {
			misses = append(misses, short(d.df.key))
		}
	}
	p("### Block misses (%d, mapped to stone)\n\n", len(misses))
	listOrNone(p, misses, 200)

	var changed []string
	for _, d := range br.decisions {
		if d.status == statusCarriedClosest || d.status == statusCarriedRenamed || d.status == statusCarriedSubst {
			changed = append(changed, fmt.Sprintf("`%s` -> `%s` (%s)", short(d.df.key), short(jd.str(d.java)), d.note))
		}
	}
	p("### Carried decisions whose Java state changed (%d)\n\n", len(changed))
	listOrNone(p, changed, 300)

	var dropped []string
	for _, d := range br.dropped {
		dropped = append(dropped, short(d.key))
	}
	p("### Previous block decisions dropped (%d): Dragonfly no longer registers the state\n\n", len(dropped))
	listOrNone(p, dropped, 100)

	p("### NeighbourDependent changes\n\n")
	if len(br.depsAdded)+len(br.depsDropped) == 0 {
		p("None.\n\n")
	}
	for _, d := range br.depsAdded {
		p("- added `%s` [%s] %s (Java block the previous tables never produced)\n", short(d.block), strings.Join(d.props, ","), d.source)
	}
	for _, d := range br.depsDropped {
		p("- dropped %s\n", d)
	}
	if len(br.depsAdded)+len(br.depsDropped) > 0 {
		p("\n")
	}
	if len(br.depsSuggested) > 0 {
		var s []string
		for _, d := range br.depsSuggested {
			s = append(s, fmt.Sprintf("%s [%s]", short(d.block), strings.Join(d.props, ",")))
		}
		p("Not added, for review: properties of Java blocks the table already produced that no Bedrock state varies\n")
		p("(%d): %s\n\n", len(s), strings.Join(s, "; "))
	}

	p("### New item decisions (%d)\n\n", len(ir.newOnes))
	var inew []string
	for _, e := range ir.newOnes {
		s := fmt.Sprintf("`%s` -> `%s` (%s", short(e.name), short(e.java), e.origin)
		if e.note != "" {
			s += "; **LOW**: " + e.note
		}
		inew = append(inew, s+")")
	}
	listOrNone(p, inew, 300)
	p("### Carried item decisions whose Java item changed (%d)\n\n", len(ir.substituted))
	var isub []string
	for _, e := range ir.substituted {
		isub = append(isub, fmt.Sprintf("`%s`: %s (%s)", short(itemLabel(e)), e.note, e.status))
	}
	listOrNone(p, isub, 300)
	p("### Item misses (%d, sent as barrier)\n\n", len(ir.misses))
	listOrNone(p, shortAll(ir.misses), 300)
	p("### Previous item decisions dropped (%d)\n\n", len(ir.dropped))
	listOrNone(p, ir.dropped, 100)

	p("### New biome decisions (%d)\n\n", len(bi.newOnes))
	var bnew []string
	for _, e := range bi.newOnes {
		bnew = append(bnew, fmt.Sprintf("%d -> `%s` (%s; %s)", e.id, short(e.java), e.origin, e.note))
	}
	listOrNone(p, bnew, 100)
	if len(bi.dropped) > 0 {
		p("Dropped: %s\n\n", strings.Join(bi.dropped, "; "))
	}

	if sr != nil {
		p("### Sounds\n\n")
		p("Bedrock playsound names are not in a Dragonfly registry, so new ones cannot be found from Dragonfly. The table is\n")
		p("carried over and checked against the Java %s sound events.\n\n", ri.javaVer)
		for _, s := range sr.renamed {
			p("- renamed %s\n", s)
		}
		for _, s := range sr.dropped {
			p("- dropped %s\n", s)
		}
		if len(sr.renamed)+len(sr.dropped) == 0 {
			p("No changes.\n")
		}
		p("\n")
	}

	p("### Java blocks no Bedrock state maps to (%d)\n\n", len(br.unreachable))
	p("Expected for Java-only blocks and for blocks picked from block entity data (bed and banner colours, flower pot\n")
	p("contents, see NeighbourDependent `<block>` entries). A new Java block in this list with a Bedrock counterpart\n")
	p("needs a hand rule or a Dragonfly block.\n\n")
	p("%s\n\n", strings.Join(shortAll(br.unreachable), ", "))

	// ---- Geyser
	if gc != nil {
		p("## GeyserMC cross-check (`%s`)\n\n", gc.dir)
		p("Geyser decides nothing here; these are the decisions it disagrees with. A carried disagreement was already in\n")
		p("the previous tables (usually a Geyser ambiguity that was resolved the other way); a new one needs a look.\n\n")
		p("| | checked | Geyser has no entry | disagreements |\n|---|---:|---:|---:|\n")
		p("| block states | %d | %d | %d |\n| items | %d | %d | %d |\n| biomes | %d | | %d |\n", gc.blockChecked, gc.blockNone, len(gc.blocks),
			gc.itemChecked, gc.itemNone, len(gc.items), gc.biomeChecked, len(gc.biomes))
		if sr != nil && sr.geyser != nil {
			p("| sounds | %d | | %d |\n", sr.geyser.checked, len(sr.geyser.diff))
		}
		p("\n")
		writeDisagreements(p, "Block states", gc.blocks, 400)
		writeDisagreements(p, "Items", gc.items, 200)
		writeDisagreements(p, "Biomes", gc.biomes, 100)
		if len(gc.itemMissing) > 0 {
			p("Dragonfly items the table lacks but Geyser maps: %s\n\n", strings.Join(gc.itemMissing, ", "))
		}
		if sr != nil && sr.geyser != nil {
			writeDisagreements(p, "Sounds", sr.geyser.diff, 100)
			if len(sr.geyser.missing) > 0 {
				p("Bedrock sound names Geyser maps that the table lacks (%d; add them to the table if Dragonfly plays them):\n%s\n\n",
					len(sr.geyser.missing), strings.Join(sr.geyser.missing, ", "))
			}
		}
	}

	// ---- Policy
	p("## How decisions are made\n\n")
	p("1. **Carry over.** Every decision in `decisions.txt` is kept by Bedrock state and Java name + properties, and\n")
	p("   compiled to the target version's ids. A Java block that lost a property keeps the closest state; a renamed one\n")
	p("   follows `javaRenames`; a removed one is decided again.\n")
	p("2. **Rules** for Bedrock states, items and biomes without a carried decision, in order:\n")
	p("   - `siblings`: other states of the same Bedrock name pick the Java block (and the properties, below).\n")
	p("   - `hand` / `hand-alias`: `handrules.go`.\n")
	p("   - `shape`: a name rewrite learned from Bedrock states with the same property names (torch -> wall_torch\n")
	p("     by torch_facing_direction), when it scores at least 0.95.\n")
	p("   - `same-name`: the Java block with the Bedrock name.\n")
	p("   - `rewrite`: name rewrites learned from the decided pairs (silver -> light_gray, double_slab -> slab,\n")
	p("     darkoak -> dark_oak, ...), most frequent first, which also bring the Java properties the rewrite always\n")
	p("     has (type=double).\n")
	p("   - `miss`: stone.\n\n")
	p("   Java properties are learned per property from the decided pairs: the Bedrock property (or pair of\n")
	p("   properties, or none) that best predicts the Java property, scored with each example left out, at the most\n")
	p("   specific level that scores at least 0.9: same Bedrock name and Java block, same Bedrock + Java property\n")
	p("   names, same Java block, all pairs. Unseen values follow an identity mapping when the evidence is one.\n")
	p("   waterlogged is always false (use `Waterlogged` when layer 1 holds water).\n\n")
	p("   Items: hand, the Java item of the Bedrock block with that name, same name, learned item then block name\n")
	p("   rewrites, else barrier. Biomes: hand (legacy biomes), same name, learned rewrites, else plains.\n")
	p("3. **nameDefault** (runtime fallback for states missing from the table) is the first decision per Bedrock name,\n")
	p("   replaced by one that is a Java default state. `NeighbourDependent` is carried over; for Java blocks the\n")
	p("   previous tables never produced, properties no Bedrock state varies are added.\n\n")

	// ---- Origins and NeighbourDependent
	origins := map[string]int{}
	for _, d := range br.decisions {
		origins[d.origin]++
	}
	var os_ []string
	for _, k := range sortedKeys(origins) {
		os_ = append(os_, fmt.Sprintf("%s %d", k, origins[k]))
	}
	p("Origins of all block decisions (kept across updates): %s.\n\n", strings.Join(os_, ", "))

	p("### Java state not determined by the Bedrock state (`javamap.NeighbourDependent()`)\n\n")
	p("Source: Neighbours = derive from adjacent blocks; Redstone = from redstone power; BlockEntity = from the block\n")
	p("entity (`<block>`: the Java block itself, for a Bedrock name shared by several Java blocks); None = Bedrock does\n")
	p("not keep it and the default renders acceptably; Unknown = not classified yet (add the property to `propSource`).\n\n")
	bySrc := map[string][]string{}
	for _, d := range br.deps {
		bySrc[d.source] = append(bySrc[d.source], fmt.Sprintf("%s [%s]", short(d.block), strings.Join(d.props, ",")))
	}
	for _, src := range sortedKeys(bySrc) {
		p("**%s** (%d): %s\n\n", strings.TrimPrefix(src, "Source"), len(bySrc[src]), strings.Join(bySrc[src], "; "))
	}
	check(os.WriteFile(filepath.Join(dir, "REPORT.md"), b.Bytes(), 0o644))
}

func listOrNone(p func(string, ...any), items []string, limit int) {
	if len(items) == 0 {
		p("None.\n\n")
		return
	}
	for i, s := range items {
		if i == limit {
			p("- ... %d more\n", len(items)-limit)
			break
		}
		p("- %s\n", s)
	}
	p("\n")
}

func writeDisagreements(p func(string, ...any), title string, ds []disagreement, limit int) {
	if len(ds) == 0 {
		return
	}
	sort.SliceStable(ds, func(i, j int) bool {
		if (ds[i].status == statusNew) != (ds[j].status == statusNew) {
			return ds[i].status == statusNew
		}
		return ds[i].what < ds[j].what
	})
	p("**%s** (new decisions first):\n\n", title)
	for i, d := range ds {
		if i == limit {
			p("- ... %d more\n", len(ds)-limit)
			break
		}
		g := d.geyser
		more := ""
		if len(g) > 3 {
			more = fmt.Sprintf(" (+%d)", len(g)-3)
			g = g[:3]
		}
		p("- `%s`: ours `%s` [%s, %s], Geyser %s%s\n", d.what, d.ours, d.status, d.origin, strings.Join(slices.Clone(g), " / "), more)
	}
	p("\n")
}
