package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"path/filepath"
	"sort"
)

// Sounds: javasession/fx_customsound_gen.go maps Bedrock playsound names to Java sound events, for sound.Custom
// names that are not Java names already. Bedrock's sound names are not in any Dragonfly registry, so new Bedrock
// names cannot be found from Dragonfly; the update keeps the table valid for the new Java version (every Java event
// must exist in registries.json) and, with -geyser, reports what Geyser's sounds.json has that the table lacks.

type soundsResult struct {
	path    string
	pairs   [][2]string
	renamed []string
	dropped []string
	geyser  *soundCheck
	javaVer string
}

func updateSounds(path string, reg javaRegistries, javaVer string) *soundsResult {
	res := &soundsResult{path: path, javaVer: javaVer}
	f := parseGo(path)
	for _, e := range compositeElts(f, "bedrockSoundNames") {
		el := e.(*ast.CompositeLit).Elts
		b, j := unquote(el[0].(*ast.BasicLit).Value), unquote(el[1].(*ast.BasicLit).Value)
		if _, ok := reg.sounds["minecraft:"+j]; !ok {
			if r, ok := soundRenames[j]; ok {
				if _, ok := reg.sounds["minecraft:"+r]; ok {
					res.renamed = append(res.renamed, fmt.Sprintf("%s: %s -> %s", b, j, r))
					j = r
				}
			}
		}
		if _, ok := reg.sounds["minecraft:"+j]; !ok {
			res.dropped = append(res.dropped, fmt.Sprintf("%s -> %s (no such Java %s sound event)", b, j, javaVer))
			continue
		}
		res.pairs = append(res.pairs, [2]string{b, j})
	}
	sort.Slice(res.pairs, func(i, j int) bool { return res.pairs[i][0] < res.pairs[j][0] })
	return res
}

func writeSounds(res *soundsResult) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by javamapupdate (internal/javamapupdate) from the previous table, checked against the Mojang %s sound events. DO NOT EDIT.\n\n", res.javaVer)
	b.WriteString("package javasession\n\n")
	b.WriteString("// bedrockSoundNames maps Bedrock playsound names to the Java sound event Geyser maps to them,\n")
	b.WriteString("// for sound.Custom names that are not Java names already.\n")
	b.WriteString("var bedrockSoundNames = [...][2]string{\n")
	for _, p := range res.pairs {
		fmt.Fprintf(&b, "\t{%q, %q},\n", p[0], p[1])
	}
	b.WriteString("}\n")
	writeGoFile(filepath.Dir(res.path), filepath.Base(res.path), b.Bytes())
}
