package v776

// The remap tables from the newest protocol (v777) to this one, generated by cmd/remapgen. The
// slices are shared: don't modify them.

// ClientboundConfiguration maps a v777 clientbound configuration packet id to this version's (-1: none).
func ClientboundConfiguration() []int32 { return clientboundConfiguration }

// ServerboundConfiguration maps this version's serverbound configuration packet id to v777's.
func ServerboundConfiguration() []int32 { return serverboundConfiguration }

// ClientboundPlay maps a v777 clientbound play packet id to this version's (-1: none).
func ClientboundPlay() []int32 { return clientboundPlay }

// ServerboundPlay maps this version's serverbound play packet id to v777's (-1: none).
func ServerboundPlay() []int32 { return serverboundPlay }

// BlockStates maps a v777 block state to this version's.
func BlockStates() []int32 { return blockStates }

// BuiltinRemap maps v777 ids to this version's (-1: none), per built-in registry.
func BuiltinRemap() map[string][]int32 { return builtin }
