// Code generated by javagen from a vanilla join capture. DO NOT EDIT.

package v777

import "embed"

//go:embed vanilla/*.bin
var vanillaFS embed.FS

// vanillaConfiguration is the configuration packets vanilla sends that we send unchanged, in order.
var vanillaConfiguration = []struct {
	ID   int32
	File string
}{
	{ClientboundConfigurationUpdateEnabledFeatures, "01_update_enabled_features.bin"},
	{ClientboundConfigurationSelectKnownPacks, "02_select_known_packs.bin"},
	{ClientboundConfigurationRegistryData, "03_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "04_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "05_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "06_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "07_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "08_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "09_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "10_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "11_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "12_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "13_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "14_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "15_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "16_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "17_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "18_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "19_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "20_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "21_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "22_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "23_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "24_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "25_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "26_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "27_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "28_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "29_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "30_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "31_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "32_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "33_registry_data.bin"},
	{ClientboundConfigurationRegistryData, "34_registry_data.bin"},
	{ClientboundConfigurationUpdateTags, "35_update_tags.bin"},
}
