// Package v777 is the Java Edition 26.3 protocol (777): packet ids, registries and the vanilla
// configuration packets, generated by java/cmd/javagen. This file is hand written.
package v777

import "sync"

// Packet is a packet id and body.
type Packet struct {
	ID   int32
	Body []byte
}

var (
	vanillaOnce sync.Once
	vanilla     []Packet
)

// VanillaConfiguration is the configuration packets a vanilla server sends unchanged, in order:
// enabled features, the known-packs offer, one registry_data per synchronised registry, and tags.
// The bodies are shared: don't modify them.
func VanillaConfiguration() []Packet {
	vanillaOnce.Do(func() {
		for _, p := range vanillaConfiguration {
			b, err := vanillaFS.ReadFile("vanilla/" + p.File)
			if err != nil {
				panic("v777: embedded " + p.File + " missing: " + err.Error())
			}
			vanilla = append(vanilla, Packet{ID: p.ID, Body: b})
		}
	})
	return vanilla
}

// RegistryID is an entry's network id in a synchronised registry, or -1.
func RegistryID(registry, entry string) int32 {
	for i, e := range Registries[registry] {
		if e == entry {
			return int32(i)
		}
	}
	return -1
}
