// Code generated by itemgen.py from Mojang's 26.3 registries report. DO NOT EDIT.

package item

// Data component types: minecraft:data_component_type protocol ids.
const (
	CompCustomData               int32 = 0   // minecraft:custom_data
	CompMaxStackSize             int32 = 1   // minecraft:max_stack_size
	CompMaxDamage                int32 = 2   // minecraft:max_damage
	CompDamage                   int32 = 3   // minecraft:damage
	CompUnbreakable              int32 = 4   // minecraft:unbreakable
	CompUseEffects               int32 = 5   // minecraft:use_effects
	CompCustomName               int32 = 6   // minecraft:custom_name
	CompMinimumAttackCharge      int32 = 7   // minecraft:minimum_attack_charge
	CompDamageType               int32 = 8   // minecraft:damage_type
	CompItemName                 int32 = 9   // minecraft:item_name
	CompItemModel                int32 = 10  // minecraft:item_model
	CompLore                     int32 = 11  // minecraft:lore
	CompRarity                   int32 = 12  // minecraft:rarity
	CompEnchantments             int32 = 13  // minecraft:enchantments
	CompCanPlaceOn               int32 = 14  // minecraft:can_place_on
	CompCanBreak                 int32 = 15  // minecraft:can_break
	CompAttributeModifiers       int32 = 16  // minecraft:attribute_modifiers
	CompCustomModelData          int32 = 17  // minecraft:custom_model_data
	CompTooltipDisplay           int32 = 18  // minecraft:tooltip_display
	CompRepairCost               int32 = 19  // minecraft:repair_cost
	CompCreativeSlotLock         int32 = 20  // minecraft:creative_slot_lock
	CompEnchantmentGlintOverride int32 = 21  // minecraft:enchantment_glint_override
	CompIntangibleProjectile     int32 = 22  // minecraft:intangible_projectile
	CompFood                     int32 = 23  // minecraft:food
	CompConsumable               int32 = 24  // minecraft:consumable
	CompUseRemainder             int32 = 25  // minecraft:use_remainder
	CompUseCooldown              int32 = 26  // minecraft:use_cooldown
	CompDamageResistant          int32 = 27  // minecraft:damage_resistant
	CompTool                     int32 = 28  // minecraft:tool
	CompWeapon                   int32 = 29  // minecraft:weapon
	CompAttackRange              int32 = 30  // minecraft:attack_range
	CompEnchantable              int32 = 31  // minecraft:enchantable
	CompEquippable               int32 = 32  // minecraft:equippable
	CompRepairable               int32 = 33  // minecraft:repairable
	CompGlider                   int32 = 34  // minecraft:glider
	CompTooltipStyle             int32 = 35  // minecraft:tooltip_style
	CompDeathProtection          int32 = 36  // minecraft:death_protection
	CompBlocksAttacks            int32 = 37  // minecraft:blocks_attacks
	CompPiercingWeapon           int32 = 38  // minecraft:piercing_weapon
	CompKineticWeapon            int32 = 39  // minecraft:kinetic_weapon
	CompAttackAnimation          int32 = 40  // minecraft:attack_animation
	CompInteractAnimation        int32 = 41  // minecraft:interact_animation
	CompAdditionalTradeCost      int32 = 42  // minecraft:additional_trade_cost
	CompBlockTransformer         int32 = 43  // minecraft:block_transformer
	CompVillagerFood             int32 = 44  // minecraft:villager_food
	CompStoredEnchantments       int32 = 45  // minecraft:stored_enchantments
	CompDye                      int32 = 46  // minecraft:dye
	CompDyedColor                int32 = 47  // minecraft:dyed_color
	CompMapId                    int32 = 48  // minecraft:map_id
	CompMapDecorations           int32 = 49  // minecraft:map_decorations
	CompMapPostProcessing        int32 = 50  // minecraft:map_post_processing
	CompChargedProjectiles       int32 = 51  // minecraft:charged_projectiles
	CompBundleContents           int32 = 52  // minecraft:bundle_contents
	CompPotionContents           int32 = 53  // minecraft:potion_contents
	CompPotionDurationScale      int32 = 54  // minecraft:potion_duration_scale
	CompSuspiciousStewEffects    int32 = 55  // minecraft:suspicious_stew_effects
	CompWritableBookContent      int32 = 56  // minecraft:writable_book_content
	CompWrittenBookContent       int32 = 57  // minecraft:written_book_content
	CompTrim                     int32 = 58  // minecraft:trim
	CompDebugStickState          int32 = 59  // minecraft:debug_stick_state
	CompEntityData               int32 = 60  // minecraft:entity_data
	CompBucketEntityData         int32 = 61  // minecraft:bucket_entity_data
	CompBlockEntityData          int32 = 62  // minecraft:block_entity_data
	CompInstrument               int32 = 63  // minecraft:instrument
	CompProvidesTrimMaterial     int32 = 64  // minecraft:provides_trim_material
	CompOminousBottleAmplifier   int32 = 65  // minecraft:ominous_bottle_amplifier
	CompJukeboxPlayable          int32 = 66  // minecraft:jukebox_playable
	CompProvidesBannerPatterns   int32 = 67  // minecraft:provides_banner_patterns
	CompRecipes                  int32 = 68  // minecraft:recipes
	CompLodestoneTracker         int32 = 69  // minecraft:lodestone_tracker
	CompFireworkExplosion        int32 = 70  // minecraft:firework_explosion
	CompFireworks                int32 = 71  // minecraft:fireworks
	CompProfile                  int32 = 72  // minecraft:profile
	CompNoteBlockSound           int32 = 73  // minecraft:note_block_sound
	CompBannerPatterns           int32 = 74  // minecraft:banner_patterns
	CompBaseColor                int32 = 75  // minecraft:base_color
	CompPotDecorations           int32 = 76  // minecraft:pot_decorations
	CompContainer                int32 = 77  // minecraft:container
	CompBlockState               int32 = 78  // minecraft:block_state
	CompBees                     int32 = 79  // minecraft:bees
	CompSulfurCubeContent        int32 = 80  // minecraft:sulfur_cube_content
	CompLock                     int32 = 81  // minecraft:lock
	CompContainerLoot            int32 = 82  // minecraft:container_loot
	CompBreakSound               int32 = 83  // minecraft:break_sound
	CompCompostable              int32 = 84  // minecraft:compostable
	CompCookingFuel              int32 = 85  // minecraft:cooking_fuel
	CompBrewingFuel              int32 = 86  // minecraft:brewing_fuel
	CompMobVisibility            int32 = 87  // minecraft:mob_visibility
	CompVillagerVariant          int32 = 88  // minecraft:villager/variant
	CompWolfVariant              int32 = 89  // minecraft:wolf/variant
	CompWolfSoundVariant         int32 = 90  // minecraft:wolf/sound_variant
	CompWolfCollar               int32 = 91  // minecraft:wolf/collar
	CompFoxVariant               int32 = 92  // minecraft:fox/variant
	CompSalmonSize               int32 = 93  // minecraft:salmon/size
	CompParrotVariant            int32 = 94  // minecraft:parrot/variant
	CompTropicalFishPattern      int32 = 95  // minecraft:tropical_fish/pattern
	CompTropicalFishBaseColor    int32 = 96  // minecraft:tropical_fish/base_color
	CompTropicalFishPatternColor int32 = 97  // minecraft:tropical_fish/pattern_color
	CompMooshroomVariant         int32 = 98  // minecraft:mooshroom/variant
	CompRabbitVariant            int32 = 99  // minecraft:rabbit/variant
	CompPigVariant               int32 = 100 // minecraft:pig/variant
	CompPigSoundVariant          int32 = 101 // minecraft:pig/sound_variant
	CompCowVariant               int32 = 102 // minecraft:cow/variant
	CompCowSoundVariant          int32 = 103 // minecraft:cow/sound_variant
	CompChickenVariant           int32 = 104 // minecraft:chicken/variant
	CompChickenSoundVariant      int32 = 105 // minecraft:chicken/sound_variant
	CompZombieNautilusVariant    int32 = 106 // minecraft:zombie_nautilus/variant
	CompFrogVariant              int32 = 107 // minecraft:frog/variant
	CompHorseVariant             int32 = 108 // minecraft:horse/variant
	CompPaintingVariant          int32 = 109 // minecraft:painting/variant
	CompLlamaVariant             int32 = 110 // minecraft:llama/variant
	CompAxolotlVariant           int32 = 111 // minecraft:axolotl/variant
	CompCatVariant               int32 = 112 // minecraft:cat/variant
	CompCatSoundVariant          int32 = 113 // minecraft:cat/sound_variant
	CompCatCollar                int32 = 114 // minecraft:cat/collar
	CompSheepColor               int32 = 115 // minecraft:sheep/color
	CompShulkerColor             int32 = 116 // minecraft:shulker/color
	CompProvidesPotteryPattern   int32 = 117 // minecraft:provides_pottery_pattern
	CompSignTextFront            int32 = 118 // minecraft:sign_text_front
	CompSignTextBack             int32 = 119 // minecraft:sign_text_back
	CompWaxed                    int32 = 120 // minecraft:waxed
	CompCushionColor             int32 = 121 // minecraft:cushion/color
)

// ComponentTypes is the number of data component types.
const ComponentTypes = 122

// componentNames are the data component type keys by protocol id.
var componentNames = [ComponentTypes]string{
	"minecraft:custom_data",
	"minecraft:max_stack_size",
	"minecraft:max_damage",
	"minecraft:damage",
	"minecraft:unbreakable",
	"minecraft:use_effects",
	"minecraft:custom_name",
	"minecraft:minimum_attack_charge",
	"minecraft:damage_type",
	"minecraft:item_name",
	"minecraft:item_model",
	"minecraft:lore",
	"minecraft:rarity",
	"minecraft:enchantments",
	"minecraft:can_place_on",
	"minecraft:can_break",
	"minecraft:attribute_modifiers",
	"minecraft:custom_model_data",
	"minecraft:tooltip_display",
	"minecraft:repair_cost",
	"minecraft:creative_slot_lock",
	"minecraft:enchantment_glint_override",
	"minecraft:intangible_projectile",
	"minecraft:food",
	"minecraft:consumable",
	"minecraft:use_remainder",
	"minecraft:use_cooldown",
	"minecraft:damage_resistant",
	"minecraft:tool",
	"minecraft:weapon",
	"minecraft:attack_range",
	"minecraft:enchantable",
	"minecraft:equippable",
	"minecraft:repairable",
	"minecraft:glider",
	"minecraft:tooltip_style",
	"minecraft:death_protection",
	"minecraft:blocks_attacks",
	"minecraft:piercing_weapon",
	"minecraft:kinetic_weapon",
	"minecraft:attack_animation",
	"minecraft:interact_animation",
	"minecraft:additional_trade_cost",
	"minecraft:block_transformer",
	"minecraft:villager_food",
	"minecraft:stored_enchantments",
	"minecraft:dye",
	"minecraft:dyed_color",
	"minecraft:map_id",
	"minecraft:map_decorations",
	"minecraft:map_post_processing",
	"minecraft:charged_projectiles",
	"minecraft:bundle_contents",
	"minecraft:potion_contents",
	"minecraft:potion_duration_scale",
	"minecraft:suspicious_stew_effects",
	"minecraft:writable_book_content",
	"minecraft:written_book_content",
	"minecraft:trim",
	"minecraft:debug_stick_state",
	"minecraft:entity_data",
	"minecraft:bucket_entity_data",
	"minecraft:block_entity_data",
	"minecraft:instrument",
	"minecraft:provides_trim_material",
	"minecraft:ominous_bottle_amplifier",
	"minecraft:jukebox_playable",
	"minecraft:provides_banner_patterns",
	"minecraft:recipes",
	"minecraft:lodestone_tracker",
	"minecraft:firework_explosion",
	"minecraft:fireworks",
	"minecraft:profile",
	"minecraft:note_block_sound",
	"minecraft:banner_patterns",
	"minecraft:base_color",
	"minecraft:pot_decorations",
	"minecraft:container",
	"minecraft:block_state",
	"minecraft:bees",
	"minecraft:sulfur_cube_content",
	"minecraft:lock",
	"minecraft:container_loot",
	"minecraft:break_sound",
	"minecraft:compostable",
	"minecraft:cooking_fuel",
	"minecraft:brewing_fuel",
	"minecraft:mob_visibility",
	"minecraft:villager/variant",
	"minecraft:wolf/variant",
	"minecraft:wolf/sound_variant",
	"minecraft:wolf/collar",
	"minecraft:fox/variant",
	"minecraft:salmon/size",
	"minecraft:parrot/variant",
	"minecraft:tropical_fish/pattern",
	"minecraft:tropical_fish/base_color",
	"minecraft:tropical_fish/pattern_color",
	"minecraft:mooshroom/variant",
	"minecraft:rabbit/variant",
	"minecraft:pig/variant",
	"minecraft:pig/sound_variant",
	"minecraft:cow/variant",
	"minecraft:cow/sound_variant",
	"minecraft:chicken/variant",
	"minecraft:chicken/sound_variant",
	"minecraft:zombie_nautilus/variant",
	"minecraft:frog/variant",
	"minecraft:horse/variant",
	"minecraft:painting/variant",
	"minecraft:llama/variant",
	"minecraft:axolotl/variant",
	"minecraft:cat/variant",
	"minecraft:cat/sound_variant",
	"minecraft:cat/collar",
	"minecraft:sheep/color",
	"minecraft:shulker/color",
	"minecraft:provides_pottery_pattern",
	"minecraft:sign_text_front",
	"minecraft:sign_text_back",
	"minecraft:waxed",
	"minecraft:cushion/color",
}

// rawKinds is how a component this package does not model is written, so it can be skipped.
var rawKinds = [ComponentTypes]uint8{
	CompCustomData:               kindNBT,
	CompMaxStackSize:             kindVarInt,
	CompMaxDamage:                kindVarInt,
	CompDamage:                   kindVarInt,
	CompUnbreakable:              kindUnit,
	CompCustomName:               kindNBT,
	CompMinimumAttackCharge:      kindFloat,
	CompItemName:                 kindNBT,
	CompItemModel:                kindString,
	CompRarity:                   kindVarInt,
	CompRepairCost:               kindVarInt,
	CompCreativeSlotLock:         kindUnit,
	CompEnchantmentGlintOverride: kindBool,
	CompIntangibleProjectile:     kindNBT,
	CompGlider:                   kindUnit,
	CompTooltipStyle:             kindString,
	CompAdditionalTradeCost:      kindVarInt,
	CompDye:                      kindVarInt,
	CompMapId:                    kindVarInt,
	CompMapDecorations:           kindNBT,
	CompMapPostProcessing:        kindVarInt,
	CompPotionDurationScale:      kindFloat,
	CompDebugStickState:          kindNBT,
	CompBucketEntityData:         kindNBT,
	CompOminousBottleAmplifier:   kindVarInt,
	CompNoteBlockSound:           kindString,
	CompBaseColor:                kindVarInt,
	CompLock:                     kindNBT,
	CompContainerLoot:            kindNBT,
	CompWolfCollar:               kindVarInt,
	CompTropicalFishBaseColor:    kindVarInt,
	CompTropicalFishPatternColor: kindVarInt,
	CompCatCollar:                kindVarInt,
	CompSheepColor:               kindVarInt,
	CompShulkerColor:             kindVarInt,
	CompWaxed:                    kindUnit,
	CompCushionColor:             kindVarInt,
}

// Potions: minecraft:potion protocol ids.
const (
	PotionWater              int32 = 0
	PotionMundane            int32 = 1
	PotionThick              int32 = 2
	PotionAwkward            int32 = 3
	PotionNightVision        int32 = 4
	PotionLongNightVision    int32 = 5
	PotionInvisibility       int32 = 6
	PotionLongInvisibility   int32 = 7
	PotionLeaping            int32 = 8
	PotionLongLeaping        int32 = 9
	PotionStrongLeaping      int32 = 10
	PotionFireResistance     int32 = 11
	PotionLongFireResistance int32 = 12
	PotionSwiftness          int32 = 13
	PotionLongSwiftness      int32 = 14
	PotionStrongSwiftness    int32 = 15
	PotionSlowness           int32 = 16
	PotionLongSlowness       int32 = 17
	PotionStrongSlowness     int32 = 18
	PotionTurtleMaster       int32 = 19
	PotionLongTurtleMaster   int32 = 20
	PotionStrongTurtleMaster int32 = 21
	PotionWaterBreathing     int32 = 22
	PotionLongWaterBreathing int32 = 23
	PotionHealing            int32 = 24
	PotionStrongHealing      int32 = 25
	PotionHarming            int32 = 26
	PotionStrongHarming      int32 = 27
	PotionPoison             int32 = 28
	PotionLongPoison         int32 = 29
	PotionStrongPoison       int32 = 30
	PotionRegeneration       int32 = 31
	PotionLongRegeneration   int32 = 32
	PotionStrongRegeneration int32 = 33
	PotionStrength           int32 = 34
	PotionLongStrength       int32 = 35
	PotionStrongStrength     int32 = 36
	PotionWeakness           int32 = 37
	PotionLongWeakness       int32 = 38
	PotionLuck               int32 = 39
	PotionSlowFalling        int32 = 40
	PotionLongSlowFalling    int32 = 41
	PotionWindCharged        int32 = 42
	PotionWeaving            int32 = 43
	PotionOozing             int32 = 44
	PotionInfested           int32 = 45
)

// Mob effects: minecraft:mob_effect protocol ids.
const (
	EffectSpeed               int32 = 0
	EffectSlowness            int32 = 1
	EffectHaste               int32 = 2
	EffectMiningFatigue       int32 = 3
	EffectStrength            int32 = 4
	EffectInstantHealth       int32 = 5
	EffectInstantDamage       int32 = 6
	EffectJumpBoost           int32 = 7
	EffectNausea              int32 = 8
	EffectRegeneration        int32 = 9
	EffectResistance          int32 = 10
	EffectFireResistance      int32 = 11
	EffectWaterBreathing      int32 = 12
	EffectInvisibility        int32 = 13
	EffectBlindness           int32 = 14
	EffectNightVision         int32 = 15
	EffectHunger              int32 = 16
	EffectWeakness            int32 = 17
	EffectPoison              int32 = 18
	EffectWither              int32 = 19
	EffectHealthBoost         int32 = 20
	EffectAbsorption          int32 = 21
	EffectSaturation          int32 = 22
	EffectGlowing             int32 = 23
	EffectLevitation          int32 = 24
	EffectLuck                int32 = 25
	EffectUnluck              int32 = 26
	EffectSlowFalling         int32 = 27
	EffectConduitPower        int32 = 28
	EffectDolphinsGrace       int32 = 29
	EffectBadOmen             int32 = 30
	EffectHeroOfTheVillage    int32 = 31
	EffectDarkness            int32 = 32
	EffectTrialOmen           int32 = 33
	EffectRaidOmen            int32 = 34
	EffectWindCharged         int32 = 35
	EffectWeaving             int32 = 36
	EffectOozing              int32 = 37
	EffectInfested            int32 = 38
	EffectBreathOfTheNautilus int32 = 39
)
