# Generates the item tables from Mojang 26.3 reports (and older versions' for old_gen.go). Run from
# go-mcjava/item, then gofmt -w *_gen.go.
import json, os, re
REP = "/root/javaproto/refs/mojang-26.3/generated/reports"
reg = json.load(open(REP + "/registries.json"))
def ordered(name):
    e = reg[name]["entries"]
    return [n for n, v in sorted(e.items(), key=lambda kv: kv[1]["protocol_id"])]
comps = ordered("minecraft:data_component_type")
items = ordered("minecraft:item")
potions = ordered("minecraft:potion")
effects = ordered("minecraft:mob_effect")

def camel(s):
    s = s.split(":", 1)[1]
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[_/]", s))

# Wire form of the components this package does not model, so a decoder can skip them.
kinds = {}
for n in ["max_stack_size","max_damage","damage","repair_cost","additional_trade_cost","rarity","dye","map_id",
          "ominous_bottle_amplifier","map_post_processing","base_color","wolf/collar","cat/collar","sheep/color",
          "shulker/color","tropical_fish/base_color","tropical_fish/pattern_color","cushion/color"]:
    kinds[n] = "kindVarInt"
for n in ["minimum_attack_charge","potion_duration_scale"]: kinds[n] = "kindFloat"
kinds["enchantment_glint_override"] = "kindBool"
for n in ["item_model","tooltip_style","note_block_sound"]: kinds[n] = "kindString"
for n in ["unbreakable","creative_slot_lock","glider","waxed"]: kinds[n] = "kindUnit"
for n in ["custom_data","intangible_projectile","map_decorations","debug_stick_state","lock","container_loot","bucket_entity_data"]:
    kinds[n] = "kindNBT"
for n in ["custom_name","item_name"]: kinds[n] = "kindNBT"

o = []
o.append("// Code generated by itemgen.py from Mojang's 26.3 registries report. DO NOT EDIT.\n\npackage item\n")
o.append("// Data component types: minecraft:data_component_type protocol ids.\nconst (")
for i, n in enumerate(comps):
    o.append("\tComp%s int32 = %d // %s" % (camel(n), i, n))
o.append(")\n\n// ComponentTypes is the number of data component types.\nconst ComponentTypes = %d\n" % len(comps))
o.append("// componentNames are the data component type keys by protocol id.\nvar componentNames = [ComponentTypes]string{")
for n in comps: o.append('\t"%s",' % n)
o.append("}\n")
o.append("// rawKinds is how a component this package does not model is written, so it can be skipped.\nvar rawKinds = [ComponentTypes]uint8{")
for i, n in enumerate(comps):
    k = kinds.get(n.split(":",1)[1])
    if k: o.append("\tComp%s: %s," % (camel(n), k))
o.append("}\n")
o.append("// Potions: minecraft:potion protocol ids.\nconst (")
for i, n in enumerate(potions):
    o.append("\tPotion%s int32 = %d" % (camel(n), i))
o.append(")\n")
o.append("// Mob effects: minecraft:mob_effect protocol ids.\nconst (")
for i, n in enumerate(effects):
    o.append("\tEffect%s int32 = %d" % (camel(n), i))
o.append(")\n")
open("components_gen.go", "w").write("\n".join(o) + "\n")

o = []
o.append("// Code generated by itemgen.py from Mojang's 26.3 registries and item component reports. DO NOT EDIT.\n\npackage item\n")
o.append("// Items is the number of Java 26.3 items (minecraft:item).\nconst Items = %d\n" % len(items))
o.append("// itemNames are the item keys by protocol id.\nvar itemNames = [Items]string{")
for n in items: o.append('\t"%s",' % n)
o.append("}\n")
ms, md = [], []
for n in items:
    c = json.load(open(REP + "/minecraft/components/item/" + n.split(":",1)[1] + ".json"))["components"]
    ms.append(c.get("minecraft:max_stack_size", 1))
    md.append(c.get("minecraft:max_damage", 0))
o.append("// defaultMaxStack is each item's default max_stack_size.\nvar defaultMaxStack = [Items]uint8{")
for i in range(0, len(ms), 32): o.append("\t" + ", ".join(str(x) for x in ms[i:i+32]) + ",")
o.append("}\n")
o.append("// defaultMaxDamage is each item's default max_damage (0: not damageable).\nvar defaultMaxDamage = [Items]uint16{")
for i in range(0, len(md), 24): o.append("\t" + ", ".join(str(x) for x in md[i:i+24]) + ",")
o.append("}\n")
open("items_gen.go", "w").write("\n".join(o) + "\n")
print(len(comps), len(items), len(potions), len(effects))

# Older protocols: each item's default max_stack_size, so a newest item sent as an older stand-in
# keeps its own stack size (see Proto).
OLD = {776: "/root/javaproto/refs/mojang-26.2/generated/reports"}
o = []
o.append("// Code generated by itemgen.py from Mojang's item component reports of older versions. DO NOT EDIT.\n\npackage item\n")
o.append("// oldMaxStack is each item's default max_stack_size in older protocols, by protocol and the protocol's item id.\nvar oldMaxStack = map[int32][]uint8{")
for proto, rep in sorted(OLD.items()):
    oreg = json.load(open(rep + "/registries.json"))
    oitems = [n for n, v in sorted(oreg["minecraft:item"]["entries"].items(), key=lambda kv: kv[1]["protocol_id"])]
    ms = [json.load(open(rep + "/minecraft/components/item/" + n.split(":",1)[1] + ".json"))["components"].get("minecraft:max_stack_size", 1) for n in oitems]
    o.append("\t%d: {" % proto)
    for i in range(0, len(ms), 32): o.append("\t\t" + ", ".join(str(x) for x in ms[i:i+32]) + ",")
    o.append("\t},")
o.append("}\n")
open("old_gen.go", "w").write("\n".join(o) + "\n")
